import 'package:pet_route_mobile/models/document_type.dart';
import 'package:pet_route_mobile/models/user.dart';

class Token {
  String _token = "";
  String _expiration = "";
  User _user = User(
      firstName: "",
      lastName: "",
      documentType: DocumentType(id: 0, description: ""),
      document: "",
      address: "",
      imageId: "",
      imageFullPath: "",
      userType: 1,
      LogerType: 0,
      fullName: "",
      id: "",
      userName: "",
      normalizedUserName: "",
      email: "",
      phoneNumber: "");

  Autogenerated(
      {required String token, required String expiration, required User user}) {
    this._token = token;
    this._expiration = expiration;
    this._user = user;
  }

  String get token => _token;
  set token(String token) => _token = token;
  String get expiration => _expiration;
  set expiration(String expiration) => _expiration = expiration;
  User get user => _user;
  set user(User user) => _user = user;

  Token.fromJson(Map<String, dynamic> json) {
    _token = json['token'];
    _expiration = json['expiration'];
    _user = User.fromJson(json['user']);
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['token'] = this._token;
    data['expiration'] = this._expiration;
    if (this._user != null) {
      data['user'] = this._user.toJson();
    }
    return data;
  }
}
